lsi: false

name: Mathew Sachin
description: My Website where I blog using jekyll
author: Mathew Sachin
url: "https://mathewsachin.github.io"

github: "MathewSachin"
twitter: "MathewSachin7"
linkedin: "mathewsachin7"

google-analytics: "UA-70778035-4"

disqus: "mathewsachin"
disqus-site: "https://mathewsachin.in"

adsense: "ca-pub-4251360406988977"

exclude: ["Gemfile", "Gemfile.lock", "README.md"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      # Default to `post` layout for posts
      layout: "post"

      # Ads shown on all posts by default
      ads: true

plugins:
  - jekyll-seo-tag  # Search Engine Optimization
  - jekyll-paginate # Pagination
  - jekyll-gist # GitHub Gists
  - jekyll-sitemap # Site Map
  - jekyll-feed # Atom Feed
  - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"
