lsi: false

name: Mathew Sachin
description: My Website where I blog using jekyll
author: Mathew Sachin
url: "https://mathewsachin.in"

github: "MathewSachin"
twitter: "MathewSachin7"
linkedin: "mathewsachin7"

google-analytics: "UA-70778035-4"

disqus: "mathewsachin"

adsense: "ca-pub-4251360406988977"

exclude: ["Gemfile", "Gemfile.lock", "README.md"]

defaults:
  # Default to `post` layout for posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # Ads shown on all pages by default
  - scope:
      path: ""
    values:
      ads: true

plugins:
  - jekyll-seo-tag  # Search Engine Optimization
  - jekyll-paginate # Pagination
  - jekyll-gist # GitHub Gists
  - jekyll-sitemap # Site Map
  - jekyll-feed # Atom Feed

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"