lsi: false

name: Mathew Sachin
description: My Website where I blog using jekyll
author: Mathew Sachin
url: "https://mathewsachin.github.io"

github: "MathewSachin"
twitter: "MathewSachin7"
linkedin: "mathewsachin7"

google-analytics: "UA-70778035-4"


adsense: "ca-pub-4251360406988977"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "node_modules", "package.json", "package-lock.json", "vendor"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      # Default to `post` layout for posts
      layout: "post"

      # Generate table of contents for all posts (shown by JS if 3+ headings)
      toc: true

      # Ads shown on all posts by default
      ads: true

plugins:
  - jekyll-seo-tag  # Search Engine Optimization
  - jekyll-paginate # Pagination
  - jekyll-gist # GitHub Gists
  - jekyll-sitemap # Site Map
  - jekyll-feed # Atom Feed
  - jekyll-redirect-from
  - jekyll-minifier # Minify HTML/CSS/JS output
  - jekyll-toc # Static table of contents

toc:
  min_level: 2
  max_level: 3

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

jekyll-minifier:
  uglifier_args:
    harmony: true
  exclude:
    - "dino/offline.js"
    - "scripts/orama.js"

picture:
  source: "images"
  output: "generated"
