lsi: false

url: "https://MathewSachin.github.io"

github: "MathewSachin"

google-analytics: "UA-70778035-3"

disqus: "mathewsachin"

adsense: "ca-pub-4251360406988977"

exclude: ["Gemfile", "Gemfile.lock", "README.md"]

# Default to `post` layout for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-seo-tag  # Search Engine Optimization
  - jekyll-paginate # Pagination
  - jekyll-gist # GitHub Gists

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"