/**
 * Maps FontAwesome CSS class strings (e.g. "fas fa-video") to icon objects
 * for use with svelte-fa. Used for data-driven icon strings that come from
 * YAML frontmatter or other string-based icon references.
 */
import type { IconDefinition } from '@fortawesome/fontawesome-common-types';
import {
  faAtom, faBolt, faBomb, faBookmark, faBrain, faBug, faCalendarDays, faCamera,
  faChartLine, faChessKnight, faClock, faCode, faCodeBranch, faCogs, faComments,
  faCookieBite, faCreditCard, faEye, faFileCode, faFilePdf, faFilm, faFlask,
  faGamepad, faGem, faGlobe, faHashtag, faHeadphones, faImage, faInfinity,
  faKeyboard, faLeaf, faMicrochip, faMobileAlt, faMoneyBillWave, faMoon, faMusic,
  faPencil, faPencilAlt, faPlayCircle, faPlug, faPuzzlePiece, faQuestionCircle,
  faRandom, faRectangleAd, faRobot, faRocket, faSatelliteDish, faSearch,
  faSeedling, faTachometerAlt, faTasks, faTerminal, faTh, faUserSecret, faUsers,
  faVideo, faVrCardboard,
} from '@fortawesome/free-solid-svg-icons';
import {
  faAndroid, faAws, faDocker, faGitAlt, faInstagram, faPinterest, faPython,
  faReddit, faTwitter, faWhatsapp, faXbox, faYoutube,
} from '@fortawesome/free-brands-svg-icons';

const ICON_MAP: Record<string, IconDefinition> = {
  'fas fa-atom': faAtom,
  'fas fa-bolt': faBolt,
  'fas fa-bomb': faBomb,
  'fas fa-bookmark': faBookmark,
  'fas fa-brain': faBrain,
  'fas fa-bug': faBug,
  'fa-solid fa-bug': faBug,
  'fas fa-calendar-days': faCalendarDays,
  'fas fa-camera': faCamera,
  'fas fa-chart-line': faChartLine,
  'fas fa-chess-knight': faChessKnight,
  'fas fa-clock': faClock,
  'fas fa-code': faCode,
  'fas fa-code-branch': faCodeBranch,
  'fas fa-cogs': faCogs,
  'fas fa-comments': faComments,
  'fas fa-cookie-bite': faCookieBite,
  'fas fa-credit-card': faCreditCard,
  'fas fa-eye': faEye,
  'fas fa-file-code': faFileCode,
  'fas fa-file-pdf': faFilePdf,
  'fas fa-film': faFilm,
  'fas fa-flask': faFlask,
  'fas fa-gamepad': faGamepad,
  'fas fa-gem': faGem,
  'fas fa-globe': faGlobe,
  'fas fa-hashtag': faHashtag,
  'fas fa-headphones': faHeadphones,
  'fas fa-image': faImage,
  'fas fa-infinity': faInfinity,
  'fas fa-keyboard': faKeyboard,
  'fas fa-leaf': faLeaf,
  'fas fa-microchip': faMicrochip,
  'fas fa-mobile-alt': faMobileAlt,
  'fas fa-money-bill-wave': faMoneyBillWave,
  'fas fa-moon': faMoon,
  'fas fa-music': faMusic,
  'fas fa-pencil': faPencil,
  'fas fa-pencil-alt': faPencilAlt,
  'fas fa-play-circle': faPlayCircle,
  'fas fa-plug': faPlug,
  'fas fa-puzzle-piece': faPuzzlePiece,
  'fas fa-question-circle': faQuestionCircle,
  'fas fa-random': faRandom,
  'fas fa-rectangle-ad': faRectangleAd,
  'fas fa-robot': faRobot,
  'fas fa-rocket': faRocket,
  'fas fa-satellite-dish': faSatelliteDish,
  'fas fa-search': faSearch,
  'fas fa-seedling': faSeedling,
  'fas fa-tachometer-alt': faTachometerAlt,
  'fas fa-tasks': faTasks,
  'fas fa-terminal': faTerminal,
  'fas fa-th': faTh,
  'fas fa-user-secret': faUserSecret,
  'fas fa-users': faUsers,
  'fas fa-video': faVideo,
  'fas fa-vr-cardboard': faVrCardboard,
  'fab fa-android': faAndroid,
  'fab fa-aws': faAws,
  'fab fa-docker': faDocker,
  'fab fa-git-alt': faGitAlt,
  'fab fa-instagram': faInstagram,
  'fab fa-pinterest': faPinterest,
  'fab fa-python': faPython,
  'fab fa-reddit': faReddit,
  'fab fa-twitter': faTwitter,
  'fab fa-whatsapp': faWhatsapp,
  'fab fa-xbox': faXbox,
  'fab fa-youtube': faYoutube,
};

export function faIconFromClass(cls: string): IconDefinition | undefined {
  return ICON_MAP[cls.trim()];
}
