name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build-site.yml
    permissions:
      contents: read
    with:
      baseurl: /pr-preview/pr-${{ github.event.pull_request.number }}
      testing: true

  deploy-preview:
    needs: build
    if: always() && (needs.build.result == 'success' || needs.build.result == 'skipped')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download site artifact
        if: github.event.action != 'closed'
        uses: actions/download-artifact@v4.1.3
        with:
          name: site
          path: ./dist

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          preview-branch: gh-pages
          pages-base-url: MathewSachin.github.io
