name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build-site.yml
    permissions: {}
    with:
      baseurl: /pr-preview/pr-${{ github.event.pull_request.number }}

  deploy-preview:
    needs: build
    if: needs.build.result == 'success' || needs.build.result == 'skipped'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Download site artifact
        if: github.event.action != 'closed'
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./_site

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site
          preview-branch: gh-pages
          pages-base-url: MathewSachin.github.io
